# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ScoreBoard.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(786, 526)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(28, 23, 731, 231))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 0, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(74)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(35)
        self.tableWidget.verticalHeader().setDefaultSectionSize(96)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "Team1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "Team2"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "1회"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "2회"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "3회"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "4회"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "5회"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "6회"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "7회"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Form", "8회"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Form", "9회"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)

        # additional code
        self.teamscore = self.read_file()
        self.add_into_table(self.teamscore)

    def read_file(self):
        data = []
        with open("score.txt", 'r') as file:
            for line in file:
                elements = line.split(',')
                elements = [element.strip() for element in elements]
                data.append(elements)

        return data

    def add_into_table(self, data_list):
        row_count = self.tableWidget.rowCount()
        self.tableWidget.setRowCount(len(data_list))
        self.tableWidget.setColumnCount(len(data_list[0]))
        for i, row_data in enumerate(data_list):
            for j, cell_data in enumerate(row_data):
                try:
                    item = QTableWidgetItem(cell_data)
                    self.tableWidget.setItem(i, j, item)

                except Exception as e:
                    print(f"Error setting item at ({i}, {j}): {e}")


import sys
from PyQt5.QtWidgets import QApplication, QTableWidgetItem, QButtonGroup, QDialog
from PyQt5.QtWidgets import QMainWindow


class BWindow(QDialog):
    def __init__(self):
        super().__init__()

        self.ui = Ui_Form()
        self.ui.setupUi(self)
        

if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = BWindow()
    window.show()
    sys.exit(app.exec_())
